import { Component } from '@angular/core';

@Component({
  selector: 'app-terms-and-conditions',
  templateUrl: './terms-and-conditions.component.html',
  styleUrl: './terms-and-conditions.component.css'
})
export class TermsAndConditionsComponent {
  termsAndCondition = "At ROBIS-Motherson, our products are the culmination of extensive research, innovation, and dedication, reflected in their unique designs, specifications, and content. These elements, which include our trademarks, logos, patents, and copyrights, are more than just symbols—they represent the essence of our brand and our commitment to excellence. As such, they are safeguarded as the exclusive intellectual property of ROBIS-Motherson, protected under both national and international laws.We respectfully request that you honor these protections by not engaging in activities such as replicating, reproducing, reverse engineering, or creating derivative works based on our products without our explicit written consent. Such actions not only undermine our efforts but also infringe upon the intellectual property that we have worked tirelessly to develop.When you purchase a product from ROBIS-Motherson, you are granted a limited, non-transferable license that allows you to use the product strictly for its intended purpose. This license is carefully designed to ensure that you enjoy the full benefits of our products while respecting the boundaries of our intellectual property rights. It is important to note that this license does not authorize you to replicate, distribute, or otherwise use the product in ways that extend beyond its intended application.We believe in the importance of protecting our intellectual property as it enables us to continue innovating and providing high-quality products to our customers. Therefore, we must make it clear that any unauthorized use, replication, or distribution of our products will be addressed through appropriate legal channels. This is not just about enforcing our rights—it’s about preserving the integrity and value of what we create.By choosing ROBIS-Motherson, you are not just purchasing a product; you are supporting a commitment to quality, innovation, and respect for intellectual property. We encourage you to review these terms and conditions periodically, as we may update or amend them to reflect changes in our business or the legal landscape. Your cooperation and understanding are greatly appreciated, and we thank you for being a part of the ROBIS-Motherson community."
}
